def aa = 'UNKNOWN'
pipeline {
  agent any
  stages {
    stage('Start') {
      steps {
        sh 'printenv'
      }
    }
    stage('Compile') {
       steps {
         dir(path: 'demoapp') {
           sh 'mvn clean'
           sh 'mvn compile'
           sh 'mvn package'
         }
       }
    }   
    stage('Docker Build') {
       steps {
         sh 'docker image prune -f'
         sh 'docker build -t $Img_Space/$App_Name:latest .'
         sh 'docker tag $Img_Space/$App_Name:latest $pv_Docker_Reg/$Img_Space/$App_Name:$Rel_Name'
       }
    }
    stage('Push to Registry') {
      steps {
        sh 'oc login $os_server:$os_port -u $os_user -p $os_pass -n $os_namespace --insecure-skip-tls-verify'
        script{
          octoken = sh(script: 'oc whoami -t', returnStdout: true)
        }
        sh "docker login $pv_Docker_Reg -u $dc_user -p ${octoken}"
        sh 'docker push $pv_Docker_Reg/$Img_Space/$App_Name:$Rel_Name'
        sh 'docker logout $pv_Docker_Reg'
      }
    }
    stage('OCP_Deploy') {
      steps {
        dir(path: 'kbdeploy/ocp4') {
          //sh 'oc login $os_server:$os_port -u $os_user -p $os_pass -n $os_namespace --insecure-skip-tls-verify'
          sh 'oc delete -f deployment.yaml || true'
          sh 'oc delete -f service.yaml || true'
          sh 'oc delete -f ingress.yaml || true'        
          sh 'oc create -f deployment.yaml'
          sh 'oc create -f service.yaml'
          sh 'oc create -f ingress.yaml'
        }
      }
    }
    stage('Logout') {
      steps {
        sh 'oc logout'
      }
    }
  }
  post { 
        always { 
            sh 'docker logout $pv_Docker_Reg || true'
            sh 'oc logout || true'
        }
  }
  environment {
    scan_img = 'false'
    os_server = 'https://api.ocp4ignite.ca.dst.ibm.com'
    os_port = '6443'
    os_user = credentials('OCP_USER')
    os_pass = credentials('OCP_PASS')
    dc_user = credentials('DC_USER')
    dc_pass = credentials('DC_PASS')
    os_namespace='demo'
    pv_Docker_Reg = 'default-route-openshift-image-registry.apps.ocp4ignite.ca.dst.ibm.com'
    Img_Space = 'demo'
    App_Name = 'demoapp'
    Rel_Name = 'latest'
  }
}
