#Example NFS PV for OCP4
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv1
  labels:
    type: nfspv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
#  storageClassName: slow
  nfs:
    path: /gv0
    server: 9.220.79.150