apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfspvc
spec:
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      type: nfspv
#  storageClassName: slow
  resources:
    requests:
      storage: 5Gi